### ISSUE TITLE
BigNumber Error: new BigNumber() not a base 16 number: 2000000NaN0000000000000000000000000NaN000000002

### ISSUE THREAD

**Issue by cwei-bgl** [mhart/kinesalite#15]
Hi Michael, Thanks for your effort. I am new to Amazon Kinesis. I am trying to set up Kinesalite in my local to assist development, but I got an error with the following simple java client code.

AmazonKinesisClient client = new AmazonKinesisClient(new BasicAWSCredentials("akid", "secret"));
client.setEndpoint("http://localhost:4567");
String streamName = "myStream1";
client.createStream(new CreateStreamRequest().withStreamName(streamName).withShardCount(2));
ByteBuffer data = ByteBuffer.wrap("myData".getBytes("UTF-8"));
PutRecordResult result = client.putRecord(streamName, data, "myPartKey");

The server is started by:
kinesalite --port 4567 --path ./kinesalite

Then Kinesalite server emitted the following error and stopped:

BigNumber Error: new BigNumber() not a base 16 number: 2000000NaN0000000000000000000000000NaN000000002
    at raise (/usr/local/lib/node_modules/kinesalite/node_modules/bignumber.js/bignumber.js:1177:25)
    at /usr/local/lib/node_modules/kinesalite/node_modules/bignumber.js/bignumber.js:1165:33
    at new BigNumber (/usr/local/lib/node_modules/kinesalite/node_modules/bignumber.js/bignumber.js:212:28)
    at Object.stringifySequence (/usr/local/lib/node_modules/kinesalite/db/index.js:168:12)
    at /usr/local/lib/node_modules/kinesalite/actions/putRecord.js:57:23
    at /usr/local/lib/node_modules/kinesalite/db/index.js:71:7
    at /usr/local/lib/node_modules/kinesalite/node_modules/level-sublevel/shell.js:102:12
    at /usr/local/lib/node_modules/kinesalite/node_modules/level-sublevel/nut.js:121:19

I tried to look into the source code of Kinesalite and print out some debug information. i inserted a console.log(...) into the first line of the method stringifySequence(obj) in index.js.

function stringifySequence(obj) {
  console.log(obj, ('00000000' + Math.floor(obj.shardCreateTime / 1000).toString(16)).slice(-9));
  ...
}

And I got the following debug information.
{ shardCreateTime: undefined,
  shardIx: undefined,
  seqIx: 0,
  seqTime: NaN } 
'000000NaN'

I wonder if there is any step I did not do correctly? Kinesalite is a very helpful local Kinesis server for development. Thanks for your contribution.

Thanks,
Cheng

**Comment by mhart** [comment]
Hey, thanks for the bug report! This is indeed an issue – I believe it's a race condition because the stream is still in the CREATING state – it should actually return an error to the client like in the real production system.

I'll patch that right now :+1:

**Comment by mhart** [comment]
Fixed and released in v1.7.1 – thanks!

**Comment by cwei-bgl** [comment]
Thanks for your quick fix, Michael.
