### ISSUE TITLE
SSL Cert CN is "Michael Hart"

### ISSUE THREAD

**Issue by jnadler** [mhart/kinesalite#16]
When a language like Java validates the SSL cert, it expects the hostname to match the CN.   Unfortunately, a domain name cannot include a space, so this cert cannot ever validate.

If the CN were "kinesalite", we could alias kinesalite to localhost in /etc/hosts, and the cert would validate.

**Comment by mhart** [comment]
Hmmm, interesting point. I'll look into this now, thanks!

**Comment by jnadler** [comment]
Thanks for the fast response!   

We'd like to use Kinesalite for automated integration tests.   For this case I would love to just turn off SSL, if the *&^% amazon libraries would make that possible.   Alas.

**Comment by mhart** [comment]
Oh – that should totally be possible in the client – it certainly is in other languages.

Lemme just check the Java API documentation, but I'm pretty sure you just need to specify your own endpoint

**Comment by mhart** [comment]
Yeah, I'm pretty sure you can just specify "http://" as part of the endpoint: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/AmazonWebServiceClient.html#setEndpoint(java.lang.String)

**Comment by mhart** [comment]
So I think this should work:

```java
AmazonKinesisClient kinesisClient = new AmazonKinesisClient(new BasicAWSCredentials("TestAccessKey","TestSecretKey"));
kinesisClient.setEndpoint("http://localhost:4567");
```

**Comment by jnadler** [comment]
We're using 3 AWS libraries - the kinesis client, along with the higher-level client and producer libraries.  

So for the raw kinesis client, what you're describing works.   But the KPL and KCL have a different config system, and it doesn't allow you to specify a protocol.   Look at this cruelty here, from KinesisProducerConfiguration.java, which correctly (I tried) states that "There is no way to disable TLS":

    /**
     * Use a custom Kinesis and CloudWatch endpoint.
     * 
     * <p>
     * Mostly for testing use. Note this does not accept protocols or paths, only host names or ip
     * addresses. There is no way to disable TLS. The KPL always connects with TLS.
     * 
     * <p><b>Expected pattern</b>: ^([A-Za-z0-9-\\.]+)?$
     */
    public KinesisProducerConfiguration setCustomEndpoint(String val) {
        if (!Pattern.matches("^([A-Za-z0-9-\\.]+)?$", val)) {
            throw new IllegalArgumentException("customEndpoint must match the pattern ^([A-Za-z0-9-\\.]+)?$, got " + val);
        }
        customEndpoint = val;
        return this;
    }

**Comment by mhart** [comment]
Bleh. Yuk. OK, will look into changing the CN.

**Comment by jnadler** [comment]
My feelings exactly.   Why the hell would they decide in 2 out of 3 clients to take a hard line on SSL, in the process making local testing very difficult?

I really appreciate you taking the time to look at this.

**Comment by mhart** [comment]
Published as v1.8.0 – lemme know if that's enough to work with

**Comment by jnadler** [comment]
Working, thank you!!

**Comment by jnadler** [comment]
For posterity, dear google searchers of the future:

To work with Amazon's higher-level Java Kinesis libraries requires ssl.  When running kinesalite under ssl, for the Kinesis Producer Library (KPL) you need to turn off cert verification:

    val config = new KinesisProducerConfiguration
    config.setCustomEndpoint("kinesalite")
    config.setPort(4567)
    config.setVerifyCertificate(false)
    config.setRegion("us-west-2")

Using Kinesis Consumer Library (KCL) is simpler, just need to set the endpoint:

    val config = new KinesisClientLibConfiguration("integrationTestTrimHorizon", "myStream", new ProfileCredentialsProvider(), "1")
      .withKinesisEndpoint("kinesalite:4567")
      .withInitialPositionInStream(InitialPositionInStream.TRIM_HORIZON)

**Comment by mhart** [comment]
Awesome, thanks for filling that in :+1:

**Comment by koustubh90** [comment]
Hi mhart,

I dont know whether this is right place to put this question. I have one issue as follow 

I am getting this error  in mod-kinesis when its trying to send message to kinesalite running locally at port 4567

 --- Endpoint: https://kinesalite:4567
Failed sending message to Kinesis, retry: 2 ...
com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream kinesisSt
ream under account 000000000000 not found. (Service: AmazonKinesis; Status Code
: 400; Error Code: ResourceNotFoundException; 

I already created kinesisStream but still facing this issue

**Comment by RichardSJust** [comment]
@koustubh90 Assuming you've checked that the stream really has been created, and the stream names are the same... It could be caused by creating the stream for an "http" the endpoint (http://kinesalite:4567) while trying to send to the "https" endpoint (https://kinesalite:4567)

**Comment by gana-freshdesk** [comment]
@jnadler hi Jeff, I am trying to use kinesalite with the exact same setup that you have mentioned. But, am getting the following error:

[error] [http_client.cc:148] Failed to open connection to kinesalite:4567 : short read

have you faced this issue before. And am using the latest version of kinesalite (1.11) and KPL (0.10.2)

**Comment by jnadler** [comment]
Nope sorry I don't recall ever seeing that error.

**Comment by j-potts** [comment]
@gana-freshdesk I'm seeing the same thing too. I'll let you know if I find a solution.

**Comment by mhart** [comment]
@gana-freshdesk @j-potts it's not related to the fact that the Java SDK has recently changed to default to CBOR is it? https://github.com/mhart/kinesalite/blob/master/README.md#cbor-protocol-issues-with-the-java-sdk

**Comment by j-potts** [comment]
@mhart Not sure yet, I was actually just about to try disabling CBOR.  😃

**Comment by j-potts** [comment]
@mhart Disabling CBOR doesn't seem to have any effect. Sadly, the HTTP client error `short read`  doesn't give us much info to work with. 😕

**Comment by gana-freshdesk** [comment]
@j-potts  sure thanks..
https://github.com/awslabs/amazon-kinesis-producer/blob/master/aws/http/http_client.cc : 148
Thats the line its coming from ..but not sure why its failing to open the connection :(

**Comment by mhart** [comment]
Hmmm, yeah, I guess it's nothing to do with the Java SDK at all – it's all their C++ tooling... which I know very little about 🤔

**Comment by j-potts** [comment]
@mhart @gana-freshdesk I got a little further. I started Kinesalite using the `--ssl` option and no longer received any `short read` errors, but instead found this:

```
[2016-07-27 09:36:23.135293] [0x0000700000187000] [error] [shard_map.cc:172] Shard map update for stream "core-test-kinesis-reliability" failed: {"__type":"ResourceNotFoundException","message":"Stream core-test-kinesis-reliability under account 000000000000 not found."};
```

**Comment by gana-freshdesk** [comment]
@j-potts  probably try creating a stream "core-test-kinesis-reliability" ?

**Comment by j-potts** [comment]
@gana-freshdesk You're right, just not sure how to create said stream in Kinesalite. 😕 

@mhart Is there doc on this?

**Comment by gana-freshdesk** [comment]
U can use aws cli to create stream ..give the endpoint as ur local
kinesalite

**Comment by j-potts** [comment]
Ah yea, my bad, I'm a Kinesis n00b and didn't realize I could point the CLI to my local instance! Thanks for your help @gana-freshdesk

**Comment by buremba** [comment]
I'm dealing with the same issue with kinesis-producer, did anyone find a solution?

**Comment by mhart** [comment]
@buremba what same issue? That the SSL Cert CN is "Michael Hart"?

**Comment by buremba** [comment]
@mhart Sorry for not being clear. The error is same as @gana-freshdesk saw:

[error] [http_client.cc:148] Failed to open connection to kinesalite:4567 : short read
