### ISSUE TITLE
Can't use kinesalite with aws-sdk

### ISSUE THREAD

**Issue by vlebedev** [mhart/kinesalite#17]
I know that this is more aws-sdk question than kinesalite, though I would like to raise it again. It was discussed already in #4 though any recipes from #4 won't work.

If I do `var kinesis = AWS.Kinesis({endpoint: new AWS.Endpoint('http://localhost:4567')});` then I got 'Missing region in config' error, but if I add region like this `var kinesis = AWS.Kinesis({endpoint: new AWS.Endpoint('http://localhost:4567'), region: 'eu-west-1'});` then my stream will be created in AWS cloud, not in kinesalite on my machine.

**Comment by mhart** [comment]
(are you accidentally missing a `new` there?)

It may be that the aws-sdk has changed since then?

The current docs are here: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Kinesis.html#constructor-property

So what happens if you just do:

```js
var kinesis = new AWS.Kinesis({endpoint: 'http://localhost:4567', region: 'us-east-1'})
```

**Comment by vlebedev** [comment]
Yes, my fault. Sorry!!!

**Comment by mhart** [comment]
Just confirmed this works using aws-sdk@2.2.9 and kinesalite@1.9.0

No problem!
