### ISSUE TITLE
Stream retention API

### ISSUE THREAD

**Issue by evansolomon** [mhart/kinesalite#18]
There are a couple new API methods to change the stream's retention period.

* http://docs.aws.amazon.com/kinesis/latest/APIReference/API_IncreaseStreamRetentionPeriod.html
* http://docs.aws.amazon.com/kinesis/latest/APIReference/API_DecreaseStreamRetentionPeriod.html

I'm not personally using them for anything, but figured I'd mention it just in case.

**Comment by lauzierj** [comment]
I have a commit for this. Setting up the pull request now.

**Comment by mhart** [comment]
Thanks to @lauzierj this was fixed in c4c3ce841a19fd1385f7cc84fb688338990c8562 – published as v1.11.0

**Comment by evansolomon** [comment]
:+1:
