### ISSUE TITLE
PutRecords should be able to partially succeed

### ISSUE THREAD

**Issue by spenczar** [mhart/kinesalite#19]
According to the Kinesis docs, PutRecords calls can partially succeed, and Kinesis will respond with a big message telling you how many record succeeded:

[Adding Multiple Records with PutRecords](http://docs.aws.amazon.com/kinesis/latest/dev/developing-producers-with-sdk.html#kinesis-using-sdk-java-putrecords)
> By default, failure of individual records within a request does not stop the processing of subsequent records in a PutRecords request. This means that a response Records array includes both successfully and unsuccessfully processed records. You must detect unsuccessfully processed records and include them in a subsequent call.

Kinesalite does not seem to match this behavior. Instead, if any record in the set is invalid, it rejects the entire batch.

Since the logic around plucking out which records are valid and which are invalid (and why!) is finicky, I'd really love it if Kinesalite matched Kinesis's behavior here.

**Comment by mhart** [comment]
@spenczar I'm not sure that's referring to invalid records – I think that's referring to records that fail to be written because of, for example, throughput limits being reached, or problems with the kinesis backend – hence why it talks about retrying them.

If you've seen otherwise can you give me some examples of the sorts of records you're talking about?

**Comment by mhart** [comment]
@spenczar how'd you go looking into this? Can you give me some example PutRecords calls where Kinesalite doesn't match Kinesis' behaviour?

**Comment by spenczar** [comment]
You're correct, and I was mistaken here, @mhart - I had observed some records get rejected for being oversized by Kinesis, and misinterpreted my own logs. Throughput limits and internal errors are the only way I can see this happening. Thanks for clearing up my confusion.

**Comment by mhart** [comment]
No probs! In an ideal world I'd incorporate ways in here to simulate throughput limits etc, but that's kind of a bigger task than I've got time for I'm afraid.
