### ISSUE TITLE
getRecords should return null iterator on closed stream

### ISSUE THREAD

**Issue by jaquadro** [mhart/kinesalite#20]
From the Kinesis documentation on the NextShardIterator response element: 

"The next position in the shard from which to start sequentially reading data records. If set to null, the shard has been closed and the requested iterator will not return any more data."

I'm trying to iterate through a lineage of shards, but a closed shard is iterating forever after reaching the end of its data.  From the code, it looks like a new iterator is returned that will keep repeating the last sequence number of the shard in its internal encoding.

**Comment by mhart** [comment]
Hi @jaquadro – I think you're right, although the documentation is a little fuzzy here:

http://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetShardIterator.html

Which says "If the shard is closed, the iterator can't return more data, and GetShardIterator returns null for its ShardIterator"

Now I haven't actually observed this to be the case in production. Every time I call `GetShardIterator` on a closed shard, it returns a `ShardIterator` as per usual.

However, calling `GetRecords` on a closed shard using this `ShardIterator` does seem to return a response without a `NextShardIterator` property.

So the documentation seems to be correct for `GetRecords`, but not for `GetShardIterator`.

In any case, thanks for spotting this! I'll fix it in kinesalite asap.

**Comment by jaquadro** [comment]
I agree, the description in GetShardIterator doesn't make much sense. Other documentation, such as after resharding:

http://docs.aws.amazon.com/kinesis/latest/dev/kinesis-using-sdk-java-after-resharding.html#kinesis-using-sdk-java-resharding-data-routing

does seem to be clear that clients should read or finish reading data in closed shards before moving on to the next shards in sequence.

Thanks for the quick response.

**Comment by mhart** [comment]
Fixed and published in v1.10.1 – thanks again for finding and reporting this!
