### ISSUE TITLE
Add support for Timestamp in GetShardIterator

### ISSUE THREAD

**Issue by mhart** [mhart/kinesalite#30]
http://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetShardIterator.html#Streams-GetShardIterator-request-Timestamp

Recently announced here: https://aws.amazon.com/blogs/aws/amazon-kinesis-update-amazon-elasticsearch-service-integration-shard-level-metrics-time-based-iterators/

**Comment by kaelumania** [comment]
@mhart I bumped into this issue, are there any plans to support this feature soon?

**Comment by rroblak** [comment]
@mhart I submitted #49 to add support for the `AT_TIMESTAMP` shard iterator type.

**Comment by mhart** [comment]
Fixed by #49
