### ISSUE TITLE
Add optional CBOR support (low priority – can disable in Java SDK)

### ISSUE THREAD

**Issue by IainMeeke** [mhart/kinesalite#31]
I am experiencing problems connecting to kinesalite using new versions of the AWS java sdk. The problem started after updating to version 1.11.0. The new versions of the sdk have no problem connecting to AWS kinesis.
Kinesalite is still working fine with the 1.10 versions.

The requests definitely get to the kinesalite, but the responses are malformed now.
Here is the error I get whenever I try to interact with kinesalite: 
`com.amazonaws.AmazonServiceException: Unable to parse HTTP response content (Service: AmazonKinesis; Status Code: 404; Error Code: null;`

**Comment by mhart** [comment]
Any idea what URL the SDK is trying to call that it's getting a 404 on?

**Comment by IainMeeke** [comment]
it looks like it is trying to access `http://<kinesalite-ip>:4567/`

**Comment by mhart** [comment]
But do you know which action it's throwing that 404 for? ie, which one of these: http://docs.aws.amazon.com/kinesis/latest/APIReference/API_Operations.html

**Comment by kellydavid** [comment]
I've also encountered similar issues. I've tried it with the `ListStreams` and `PutRecord` actions and have had the result that @IainMeeke described above.

**Comment by mhart** [comment]
I guess this must be something specific to the Java SDK? The latest JS and Python libraries work fine (and so does the CLI):

```console
$ aws kinesis list-streams --endpoint-url 'http://localhost:4567'
{
    "StreamNames": []
}
```

I don't know enough about the Java SDK to know what they've changed – does it have debugging capabilities or something?

**Comment by kellydavid** [comment]
The aws cli works with the actions I mentioned above. It's the sdk that appears to have changed something.

**Comment by mhart** [comment]
Is there a chance the Java SDK is trying to talk CBOR to kinesalite instead of JSON? I noticed this in the release notes for 1.11.3:

> Amazon Kinesis now supports Concise Binary Object Representation (Cbor) data format

Could it be using that by default? (the `Content-Type` would probably be `application/x-amz-cbor-1.1`)

This is the first I've heard of Amazon supporting that – kinesalite still only supports `application/x-amz-json-1.1` – if this is the case, is there a config setting to change the Java SDK to use JSON?

**Comment by kellydavid** [comment]
It looks like the 1.11.x sdk does in fact send requests in the `application/x-amz-cbor-1.1` format by default

**Comment by mhart** [comment]
Right, that would be it then. Can you see a way to override that for the SDK at least? It will take a bit of work to get kinesalite to support CBOR

**Comment by twosider** [comment]
For disabling CBOR, see:

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/constant-values.html#com.amazonaws.SDKGlobalConfiguration.AWS_CBOR_DISABLE_SYSTEM_PROPERTY

**Comment by mhart** [comment]
@twosider oh great! thanks. Looks like you can also set an environment variable, `AWS_CBOR_DISABLE`:

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html#AWS_CBOR_DISABLE_ENV_VAR

@IainMeeke let me know if that works for you

**Comment by schickling** [comment]
@mhart works for me! Would be great if you could mention it in the Readme :)

**Comment by mhart** [comment]
@schickling sorry, finally got around to doing this! https://github.com/mhart/kinesalite/blob/master/README.md#cbor-protocol-issues-with-the-java-sdk

**Comment by whummer** [comment]
+1, `AWS_CBOR_DISABLE` works for us, too. Thanks for updating.

**Comment by Liorba** [comment]
Hey can you please share a code snippet on how you used this property?
I'm using kinesis client and it seems that cbor is enabled by
[default](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-kinesis/src/main/java/com/amazonaws/services/kinesis/AmazonKinesisClient.java#L76)

**Comment by mhart** [comment]
@Liorba just set `AWS_CBOR_DISABLE` in your environment variables. Eg, if you're on bash shell in linux:

```bash
export AWS_CBOR_DISABLE=1
```

Then you should be able to use your kinesis client from that session.

**Comment by bobtiernay-okta** [comment]
Would be nice to incorporate https://www.npmjs.com/package/cbor if possible.

**Comment by lyi2012** [comment]
It appears to have some validation errors with tmccombs fork, and the a fix is available from https://github.com/lyi2012/kinesalite

**Comment by alins** [comment]
now only if we can get all these approved and merged, that would be awesome

**Comment by bobtiernay-okta** [comment]
https://github.com/tmccombs Thanks for taking this on! @mhart any thoughts on merging the PR?

**Comment by mhart** [comment]
Merged and shipped in v3.3.0 – thanks all!

**Comment by teracross** [comment]
Note - in order for us to get this working with the Kinesis Client Library we needed to use aws.cborEnabled=false instead in our environment variables.

**Comment by mhart** [comment]
@teracross can you elaborate a little? with the latest release you shouldn't need to set anything

**Comment by teracross** [comment]
Sure, this is the maven dependency that we are using for the Kinesis Client Library in our Java 1.8 project:         

> <dependency>
>             <groupId>software.amazon.kinesis</groupId>
>             <artifactId>amazon-kinesis-client</artifactId>
>             <version>2.1.3</version>
> </dependency>

While trying to communicate with an instance of localstack running on Docker on my Mac, we noticed that we were getting 502 errors from LocalStack when trying to communicate with Kinesis. Using Wireshark we determined that the Kinesis Client Library was sending a request to LocalStack using the cbor based protocol. In response, a 502 error was returned to the Kinesis Client Library from localstack. 

This might have to do with the version of the Kinesis Client Library that we are using, but just wanted to document this in case anyone else might encounter the same issue.

**Comment by mhart** [comment]
@teracross are you sure localstack is using the version that has this feature in? It was only released in v3.3.0 2 days ago.

See: https://github.com/mhart/kinesalite/issues/31#issuecomment-563415353

**Comment by teracross** [comment]
We are not specifying a LocalStack version, so my assumption is that whichever image that is tagged as "latest" is probably being used. 

Was not aware that an update for this specific issue was released 2 days ago, so that is a possibility.

**Comment by alins** [comment]
LocalStack? you are in the wrong place my friend. pretty sure they haven't integrated this change yet
