### ISSUE TITLE
Add triggers

### ISSUE THREAD

**Issue by ganddev** [mhart/kinesalite#39]
Hello,

is it possible to add triggers to a stream. So my infrastructure is based on aws lambda and kinesis or more precisely my lambda function get triggered from an aws kinesis stream. Is it possible to add these triggers in this kinesis streams?

Thanks in advance.

**Comment by mhart** [comment]
This project's aim is to replicate the Kinesis AWS API, which doesn't handle the triggering of Lambda's or anything similar.

I suspect behind the scenes that AWS are using the [KCL](http://docs.aws.amazon.com/streams/latest/dev/developing-consumers-with-kcl.html) or something similar to read events from your Kinesis stream (in batches) and then invoke your Lambda function – so I'd investigate using that to achieve this aim. You could also use https://github.com/mhart/kinesis to read from your stream and invoke your function too.
