### ISSUE TITLE
Connecting from Browser SDK

### ISSUE THREAD

**Issue by Erve1879** [mhart/kinesalite#4]
I'm hoping to use Kinesalite to test my web app locally (using the AWS JS SDK, I post data to Kinesis from the browser). 

I've started Kinesalite using `kinesalite 4567` in my terminal and in my browser config I have:

````JavaScript
var ep = new AWS.Endpoint('https://127.0.0.1:4567');
var kinesis = new AWS.Kinesis({endpoint: ep});
````
But the SDK of course complains about missing credentials and region settings. Is what I'm trying to achieve possible?

Thanks

**Comment by mhart** [comment]
It might be - I'm a little rusty on the SDK itself, but it seems that it's the one complaining, not kinesalite itself, so it's probably just a matter of supplying some credentials and region.

What happens if you do:
```js
var kinesis = new AWS.Kinesis({
  endpoint: new AWS.Endpoint('https://127.0.0.1:4567'),
  region: 'us-east-1',
  accessKeyId: 'akid',
  secretAccessKey: 'secret',
})
```
Or:
```js
AWS.config.update({region: 'us-east-1', accessKeyId: 'akid', secretAccessKey: 'secret'})

var kinesis = new AWS.Kinesis({endpoint: new AWS.Endpoint('https://127.0.0.1:4567')})
```

**Comment by Erve1879** [comment]
Thanks @mhart - I'm now getting the SSL cert error (refuses to accept the SSL cert). Have tried using `http://` and setting `enableSSL: false`, but that gives me a `connection dropped` error instead. I'm going to try using the code from here https://github.com/mhart/kinesalite/pull/3 to see if that solves the issue for me.

**Comment by Erve1879** [comment]
@mhart - PR #3 works a charm for me. However, I'm now suffering from CORS errors.... I've tried adding the correct headers to the node http server, but not getting anywhere. Any chance you can point me in the right direction? Thanks again.

**Comment by mhart** [comment]
Hmmm, that's a good point. I think adding headers is the right way to go, but might need some playing around.

I don't have much time in the next few days unfortunately, but I'll be on a place Monday, so will have plenty of time to look into it then (and I'll merge PR #3 in, or some variant of it)

**Comment by Erve1879** [comment]
Super, thanks @mhart. Much appreciated. Trying to get my local test env up and running and emulating Kinesis is the final piece of the puzzle! 

Bit bemused that AWS haven't released something like this (as they did with DynamoDBLocal)....

**Comment by Erve1879** [comment]
@mhart - did you have a chance to take a look at this?

**Comment by mhart** [comment]
Hey, sorry for the delay, just merged #3 and will look into the CORS stuff now

**Comment by mhart** [comment]
Fixed in v0.6.0

**Comment by mhart** [comment]
(oh, and thanks for filing the issue!)

**Comment by Erve1879** [comment]
Brilliant, thanks @mhart - will try it out a little later. Going to be really helpful!

**Comment by mhart** [comment]
Well... I'm sure it will be as soon as I've actually finished implementing `GetRecords` :-)

**Comment by Erve1879** [comment]
Selfishly, I'm only interested in `PutRecord`.....!

**Comment by mhart** [comment]
Oh awesome, well you should be covered then :+1:

**Comment by mhart** [comment]
Just to update from a question posed at #17 – you no longer need an explicit `AWS.Endpoint` and can just do:

```js
var kinesis = new AWS.Kinesis({endpoint: 'http://localhost:4567', region: 'us-east-1'})
```
