### ISSUE TITLE
Is any memory limitation on putting data into kinesis stream with put-record?

### ISSUE THREAD

**Issue by lucianonet** [mhart/kinesalite#57]
I tried to put content of a file that has more than 260 kb but I got an error.
The put-record commands looks like:  aws kinesis put-record --stream-name kinesis_stream_name --data "$(cat file.xml)" --partition-key "test" --endpoint-url http://127.0.0.1:4567 --no-verify-ssl --profile local
And the error is: -bash: /usr/local/bin/aws: Argument list too long.
For files that are smaller that 260 kb seems to work fine. I removed from file.xml some content and after that worked properly.

**Comment by mhart** [comment]
That error looks like it's coming from the AWS CLI tool to me?

**Comment by lucianonet** [comment]
Yes, but I thought that is related to kinesalite which is used behind the scene.

**Comment by mhart** [comment]
No, that error's saying the argument list that you're passing to the aws tool is too long - it hasn't even reached kinesalite yet

**Comment by lucianonet** [comment]
Thank you.
