### ISSUE TITLE
Add support for the new `listShards` API

### ISSUE THREAD

**Issue by kalyanaramansanthanam** [mhart/kinesalite#59]
Please add support for ListShards API
https://aws.amazon.com/about-aws/whats-new/2018/02/10x-higher-api-call-rates-for-amazon-kinesis-client-library-kcl-applications/

https://docs.aws.amazon.com/kinesis/latest/APIReference/API_ListShards.html
https://github.com/awslabs/amazon-kinesis-client/releases/tag/v1.9.0

**Comment by robwil** [comment]
+1

**Comment by aneberhardt** [comment]
+1

**Comment by etspaceman** [comment]
+1

**Comment by oriy** [comment]
please review https://github.com/mhart/kinesalite/pull/64 ... partial implementation

**Comment by mhart** [comment]
Added in v1.13.0
