### ISSUE TITLE
Non-monotonic shard iterator returned from GetRecords 

### ISSUE THREAD

**Issue by studzien** [mhart/kinesalite#62]
Hi.
I believe I encountered an issue where the `NextShardIterator` returned from `GetRecords`, that seems to happen under two circumstances:
- Sometimes `GetRecords` returns empty records and
- `GetRecords` is called more often than every second

A test showing this behaviour is here: https://github.com/studzien/kinesalite/commit/078e994a794509786ab7cb0752360617e8b2bb0a
I apologise if it's not clear enough, I haven't used Javascript for a while :)

From a very quick overview of the code it looks to me that the root cause of the problem is rounding the sequence time to the floor of a second (1000 millis).

The sequence is more or less as follows:
1. we put some records
2. first `GetRecords` is done with the iterator pointing at the beginning of the stream
3. we get the current records, and the next shard iterator is pointing behind the last record (`now + 1000`)
4. we get records with the new shard iterator, result is empty and the next shard iterator is pointing at the last record in the stream
5. we get records again, and since the lookup range is `gte`, we go back to 3, except we just fetch the last record.

I feel like the best approach to fix the above mismatch would be to get rid of rounding to 1000 milliseconds. And use 1 as an offset instead of 1000.

What do you think? I can try to fix it if this approach makes sense.
If my reasoning is incorrect, please let me know, what I've missed :)

Thanks and best regards!

**Comment by sdaclin** [comment]
Hello,

I experience the same problem on my project : 

- my inttest poll the kinesis shard up to 5 times / sec (regarding kinesis limit of transaction per seconds per shard)
- with localstack (kinesalite) I can recover twice the same record
- with kinesis all inttest are OK

If you implement a fix I can help with the QA regarding to my tests.

Regards

**Comment by studzien** [comment]
Hey @sdaclin 
I did a pretty hacky fix in this commit: 
https://github.com/studzien/kinesalite/commit/cc0dc79d9733303e7ec0b423e3e8ecc5f391da0a

For me it solves the problem.

**Comment by sdaclin** [comment]
Rafal,
I've just tried your fix and it works pretty well. Good job 👍 
I've not reviewed your code but I assume you should do a pull request to reintegrate your change to kinesalite.
Thanks in advance,
Regards

**Comment by sdaclin** [comment]
To @futureMe : make a pull request to localstack once this change release with kinesalite.

**Comment by studzien** [comment]
Hi again @sdaclin , it seems that the issue has been recently (since 1.11.7), with this (cherry-picked?) commit:
https://github.com/mhart/kinesalite/commit/d122948de59ce06e007f32581b96823c68c5b42c

If the current version works for you too, I will close this issue.

Thanks!

**Comment by sdaclin** [comment]
Yes, you're right all tests are green !
As I got the issue through localstack project I didn't even tried with kinesalite LATEST.
To me the issue could be closed.
I'm going to propose an upgrade of version to the localstack team if necessary.
Thanks a lot for your help.
Regards

**Comment by sdaclin** [comment]
https://github.com/localstack/localstack/issues/687

**Comment by studzien** [comment]
I still created a PR with the test, for regression (#66)
