### ISSUE TITLE
listShards doesn't respect ExclusiveStartShardId

### ISSUE THREAD

**Issue by EugeneYushin** [mhart/kinesalite#76]
[listShards.js](https://github.com/mhart/kinesalite/blob/master/actions/listShards.js) method returns all shards with no respect to optional [ExclusiveStartShardId](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_ListShards.html#Streams-ListShards-request-ExclusiveStartShardId)

This results in manual exclusion of shard ids. Example from Flink codebase:
https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxy.java#L457

**Comment by EugeneYushin** [comment]
PR:
https://github.com/mhart/kinesalite/pull/77

**Comment by tweise** [comment]
@mhart could you please take a look at this? It would be great to get this change. We use Kinesalite for testing and this issue basically makes it difficult to use with legit Kinesis consumer code. 

Or are there other maintainers that we could reach out to?

**Comment by mhart** [comment]
Fixed in v1.15.0

**Comment by tweise** [comment]
Awesome, thanks!
