### ISSUE TITLE
Server returns 400 response for data near size cap

### ISSUE THREAD

**Issue by Daenyth** [mhart/kinesalite#9]
I tried sending a buffer with size 50268, the size cap is 51200. I get this:

```
com.amazonaws.AmazonServiceException: 1 validation error detected: Value 'java.nio.HeapByteBuffer[pos=0 lim=50268 cap=50268]' at 'data' failed to satisfy constraint: Member must have length less than or equal to 51200 (Service: AmazonKinesis; Status Code: 400; Error Code: ValidationException; Request ID: bc34b080-ce51-11e4-a42f-631ec68de648)
```

The code works correctly in production and does not give this error.

**Comment by Daenyth** [comment]
It looks like the test covers over-limit but it does not test that data under the size limit is valid. https://github.com/mhart/kinesalite/blob/6190a29ad73893f809a291ec2b4afa12a7cb2836/test/putRecords.js#L78

**Comment by mhart** [comment]
Excellent point! I'll add those tests now – and fix up whatever issue's surfacing there.

**Comment by Daenyth** [comment]
I wonder if the bug might be here: https://github.com/mhart/kinesalite/blob/d78e2ccce85c108674894ac427cac2b5e852847c/validations/index.js#L229

**Comment by Daenyth** [comment]
So far I'm tweaking my buffer configs and it seems like 37kb is accepted, 40kb is rejected. I'll try to pin down a more exact number

**Comment by mhart** [comment]
I think I probably just need to convert the base64 to a buffer before checking the length

**Comment by Daenyth** [comment]
I'm not familiar with js/node but that sounds plausible

**Comment by mhart** [comment]
Just grabbing some lunch, but will fix in a sec :+1:

**Comment by Daenyth** [comment]
Thanks! I appreciate it. 38kb works, 39kb does not :)

**Comment by mhart** [comment]
Yeah, base64 usually increases the size 4/3 – so 38*4/3 ~= 51

**Comment by mhart** [comment]
Ok, try v1.0.4 – I think I've fixed it, but I haven't added tests yet – I'll do that in a sec.

**Comment by mhart** [comment]
Added tests in 9937449 and tested on production. Gonna close this, but feel free to reopen if you keep seeing issues.

Thanks for the report!

**Comment by Daenyth** [comment]
I can confirm it's now fixed. Thanks a ton for the fast response!
