### ISSUE TITLE
Creating streams takes rather long

### ISSUE THREAD

**Issue by johannes-gehrs** [mhart/kinesalite#97]
We use kinesalite 3.1.0 from localstack. We notice that creating streams takes quite some time, slowing down our integration tests. 

Is there any way we can speed up kinesalite in creating the streams? 

Alternatively, is there a way we could contribute to the project such that the creation of streams is potentially sped up?

**Comment by mhart** [comment]
Yup, see the README – `createStreamMs`, etc

**Comment by johannes-gehrs** [comment]
excellent. Thank you so much and sorry for bothering you with something which is clearly mentioned in the README.
